name: Install kubectl

on:
  push:
    branches:
      - main

jobs:
  install_kubectl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download kubectl binary
      run: |
        K8S_VERSION=$(curl -L -s https://dl.k8s.io/release/stable.txt)
        curl -LO "https://dl.k8s.io/release/${K8S_VERSION}/bin/linux/amd64/kubectl"

    - name: Validate kubectl binary
      run: |
        curl -LO "https://dl.k8s.io/release/${K8S_VERSION}/bin/linux/amd64/kubectl.sha256"
        echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check

    - name: Install kubectl
      run: |
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    - name: Verify kubectl installation
      run: kubectl version --client --output=yaml
