name: Install kubectl, Docker, and Initialize Kubernetes

on:
  push:
    branches:
      - main

jobs:
  install_kubectl_docker_and_k8s:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove conflicting Kubernetes GPG key and sourcelist.d
        run: |
          sudo rm -f /etc/apt/keyrings/kubernetes.gpg
          sudo rm -rf /etc/apt/sources.list.d/*

      - name: Add Docker GPG key
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor --batch --yes -o /usr/share/keyrings/docker-archive-keyring.gpg

      - name: Set up Docker repository
        run: |
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

      - name: Re-add Kubernetes GPG key (if needed)
        run: |
          curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /etc/apt/keyrings/kubernetes.gpg

      - name: Install Docker dependencies
        run: |
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

      - name: Download kubectl binary
        run: |
          K8S_VERSION=$(curl -L -s https://dl.k8s.io/release/stable.txt)
          curl -LO "https://dl.k8s.io/release/${K8S_VERSION}/bin/linux/amd64/kubectl"
          
      - name: Install Docker
        run: |
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo systemctl start docker
          sudo systemctl enable docker
          docker --version

      - name: Verify kubectl installation
        run: kubectl version --client --output=yaml

      - name: Verify Docker installation
        run: docker --version

      - name: Install kubeadm, kubelet, and kubectl
        run: |
          sudo apt install -y kubelet kubeadm kubectl

      - name: Install and configure containerd
        run: |
          sudo mkdir -p /etc/containerd
          sudo apt install -y containerd
          sudo containerd config default | sudo tee /etc/containerd/config.toml
          sudo sed -i 's/            SystemdCgroup = false/            SystemdCgroup = true/' /etc/containerd/config.toml
          sudo systemctl daemon-reload
          sudo systemctl restart containerd

      - name: Remove existing Kubernetes master node
        run: |
          sudo kubeadm reset -f
          rm -rf  /etc/cni/net.d
          rm $HOME/.kube/config


      - name: Initialize Kubernetes master node
        run: |
          sudo kubeadm init
          sudo cp /etc/kubernetes/admin.conf $HOME/
          sudo chown $(id -u):$(id -g) $HOME/admin.conf
          echo 'export KUBECONFIG=$HOME/admin.conf' >> $HOME/.bashrc
          export KUBECONFIG=$HOME/admin.conf
          kubectl get nodes

      - name: Install curl
        run: sudo apt-get install -y curl

      - name: Download and Apply Calico
        run: |
          curl -LO https://docs.tigera.io/archive/v3.25/manifests/calico.yaml
          if [ -s calico.yaml ]; then
            kubectl apply -f calico.yaml --validate=false
          else
            echo "Calico manifest download failed." && exit 1
          fi

      - name: Untaint Control-Plane Nodes
        run: |
          kubectl taint nodes --all node-role.kubernetes.io/control-plane-
          kubectl taint nodes --all key:NoSchedule-

