name: Install kubectl, Docker, and Initialize Kubernetes

on:
  push:
    branches:
      - main

jobs:
  install_kubectl_docker_and_k8s:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download kubectl binary
      run: |
        K8S_VERSION=$(curl -L -s https://dl.k8s.io/release/stable.txt)
        curl -LO "https://dl.k8s.io/release/${K8S_VERSION}/bin/linux/amd64/kubectl"

    - name: Install kubectl
      run: |
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    - name: Verify kubectl installation
      run: kubectl version --client --output=yaml

    - name: Install Docker
      run: |
        sudo apt update
        sudo apt -y install docker.io
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Verify Docker installation
      run: docker --version

    - name: Install kubeadm, kubelet, and kubectl
      run: |
        sudo apt update
        sudo apt install -y apt-transport-https curl
        curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /etc/apt/trusted.gpg.d/kubernetes.asc
        sudo apt update
        sudo apt install -y kubelet kubeadm kubectl

    - name: Initialize Kubernetes master node
      run: |
        sudo kubeadm init

    - name: Set up kubeconfig
      run: |
        mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config

    - name: Verify Kubernetes setup
      run: kubectl get nodes

      - name: Set up Docker
        run: |
          # Update the package database and install required dependencies
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

          # Add Docker’s official GPG key
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

          # Set up the stable Docker repository
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

          # Install the latest version of Docker
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Verify Docker installation
        run: docker --version
