name: Install Latest kubectl

on:
  push:
    branches:
      - main

jobs:
  install-kubectl:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          # Installing Docker
          sudo apt update
          sudo apt -y install docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          echo "Docker installation complete."

      - name: Install Kubernetes and fix GPG key
        run: |
          # Fix GPG key for Kubernetes repository
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          
          # Add Kubernetes repository
          sudo apt-add-repository "deb https://apt.kubernetes.io/ kubernetes-xenial main"
          
          # Update package list
          sudo apt update

          # Install kubeadm, kubelet, and kubectl
          sudo apt install -y kubeadm kubelet kubectl
          sudo apt-mark hold kubelet kubeadm kubectl

          # Disable swap for Kubernetes
          sudo swapoff -a
          sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
          sudo kubeadm init
          echo "Kubernetes successfully installed."

          # Set KUBECONFIG for Kubernetes
          export KUBECONFIG=/etc/kubernetes/admin.conf
          echo "Kubeconfig set for Kubernetes."

          # Install containerd
          sudo mkdir -p /etc/containerd
          sudo apt install -y containerd
          sudo containerd config default | sudo tee /etc/containerd/config.toml
          sudo sed -i 's/            SystemdCgroup = false/            SystemdCgroup = true/' /etc/containerd/config.toml
          sudo systemctl daemon-reload
          sudo systemctl restart containerd
          echo "Containerd installation complete."

      - name: Download kubectl using stable version
        run: |
          # Fetch the latest stable version of kubectl
          VERSION=$(curl -s https://dl.k8s.io/release/stable.txt)
          
          # Construct the URL to download kubectl and ensure it's correct
          URL="https://dl.k8s.io/release/${VERSION}/bin/linux/amd64/kubectl"
          echo "Download URL: $URL"
          curl -LO "$URL"

      - name: Install kubectl
        run: |
          # Make kubectl executable
          chmod +x ./kubectl
          
          # Move kubectl to /usr/local/bin
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Verify kubectl version
        run: kubectl version --client
