name: Install kubectl, Docker, and Initialize Kubernetes

on:
  push:
    branches:
      - main

jobs:
  install_kubectl_docker_and_k8s:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove conflicting Kubernetes GPG key
        run: |
          sudo rm -f /etc/apt/keyrings/kubernetes.gpg

      - name: Add Docker GPG key
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor --batch --yes -o /usr/share/keyrings/docker-archive-keyring.gpg

      - name: Set up Docker repository
        run: |
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

      - name: Re-add Kubernetes GPG key (if needed)
        run: |
          curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes.gpg

      - name: Update package database
        run: |
          sudo apt-get update

      - name: Install Docker dependencies
        run: |
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

      - name: Install Docker
        run: |
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Download kubectl binary
        run: |
          K8S_VERSION=$(curl -L -s https://dl.k8s.io/release/stable.txt)
          curl -LO "https://dl.k8s.io/release/${K8S_VERSION}/bin/linux/amd64/kubectl"

      - name: Install kubectl
        run: |
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Verify kubectl installation
        run: kubectl version --client --output=yaml

      - name: Install Docker (alternative)
        run: |
          sudo apt update
          sudo apt -y install docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Verify Docker installation
        run: docker --version

      - name: Install kubeadm, kubelet, and kubectl
        run: |
          sudo apt update
          sudo apt install -y apt-transport-https curl
          curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /etc/apt/trusted.gpg.d/kubernetes.asc
          sudo apt update
          sudo apt install -y kubelet kubeadm kubectl

      - name: Initialize Kubernetes master node
        run: |
          sudo kubeadm init

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
          sudo chown $(id -u):$(id -g) $HOME/.kube/config
