name: Remove Docker and Kubernetes

on:
  push:
    branches:
      - main

jobs:
  remove-docker-kubernetes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Remove Kubernetes packages and repositories
      run: |
        # Remove Kubernetes components (kubelet, kubeadm, kubectl)
        if dpkg-query -l | grep -q -E 'kubeadm|kubelet|kubectl|kubernetes'; then
          echo "Removing Kubernetes packages..."
          sudo apt-get purge -y kubeadm kubelet kubectl kubernetes
          sudo rm -f /etc/apt/sources.list.d/kubernetes.list
        else
          echo "No Kubernetes packages found to remove."
        fi
        sudo apt-get autoremove -y

    - name: Remove Docker packages and repositories
      run: |
        # Purge Docker and related components
        if dpkg-query -l | grep -q -E 'docker|containerd|runc'; then
          echo "Removing Docker..."
          sudo apt-get purge -y docker docker-engine docker.io containerd runc
          sudo apt-get autoremove -y
        else
          echo "No Docker packages found to remove."
        fi
        sudo rm -f /etc/apt/sources.list.d/docker.list
        
        # Remove Docker binary if it exists
        sudo rm -f /usr/bin/docker
        sudo rm -f /usr/local/bin/docker

        # Stop and disable Docker services
        sudo systemctl stop docker
        sudo systemctl disable docker
        sudo rm -f /etc/systemd/system/docker.service
        sudo rm -f /etc/systemd/system/docker.socket

        # Remove Docker networks and containers
        if command -v docker &>/dev/null; then
          sudo docker container prune -f
          sudo docker network prune -f
        fi

    - name: Reboot the system
      run: |
        echo "Rebooting the system to complete the uninstallation."
        sudo reboot
