name: Remove Kubernetes, Kubeadm, and Docker

on:
  push:
    branches:
      - #main

jobs:
  remove-k8s-docker:
    runs-on: self-hosted

    steps:
      # Step 1: Check if Docker is installed and remove it
      - name: Remove Docker if installed
        run: |
          if dpkg-query -l | grep -q -E 'docker|docker-engine|docker.io|containerd'; then
            echo "Removing Docker and related packages..."
            sudo apt-get remove --purge -y docker docker-engine docker.io containerd runc
            sudo rm -f /etc/apt/sources.list.d/docker.list
          else
            echo "No Docker packages found to remove."
          fi

      # Step 2: Remove Kubernetes and Kubeadm if installed
      - name: Remove Kubernetes and Kubeadm if installed
        run: |
          if dpkg-query -l | grep -q -E 'kubeadm|kubelet|kubectl|kubernetes'; then
            echo "Removing Kubernetes and Kubeadm..."
            # Unhold any held packages
            sudo apt-mark unhold kubeadm kubectl kubelet || true
            sudo apt-get remove --purge -y kubeadm kubelet kubectl kubernetes
            sudo rm -f /etc/apt/sources.list.d/kubernetes.list
          else
            echo "No Kubernetes packages found to remove."
          fi

      # Step 3: Clean up unused dependencies
      - name: Clean up unused packages and dependencies
        run: |
          sudo apt-get autoremove -y
          sudo apt-get clean

      # Step 4: Remove old Kubernetes packages
      - name: Remove old Kubernetes packages
        run: |
          # Remove Kubernetes-related packages
          sudo apt-get remove --purge -y kubeadm kubelet kubectl kubernetes
          # Clean up any residual configuration files
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo rm -rf /etc/kubernetes
          sudo rm -f /etc/apt/sources.list.d/kubernetes.list

      # Step 5: Remove Kubernetes GPG key and reconfigure repository
      - name: Remove Kubernetes GPG key and reconfigure repository
        run: |
          # Remove Kubernetes GPG key
          sudo apt-key del 7BB9C367
          
          # Ensure that the old Kubernetes repository is removed
          sudo rm -f /etc/apt/sources.list.d/kubernetes.list
          
          # Reconfigure the repository (optional, depending on need)
          echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
          
          # Update package list after removal
          sudo apt-get update

